
# all - install all certificates
# region list - use any combination
# 7282
# au-syd
# br-sao
# ca-mon
# ca-tor
# ca_che
# ca_che_v2
# ca_mon_v2
# dal_preprod
# dal_preprod_tls
# dev13
# dev13_tls
# dev42
# dev58
# dev80
# dev83
# dev92
# dev93
# eu-de
# eu-es
# eu-fr2
# eu-gb
# in-mum
# int_in-mum
# jp-osa
# jp-tok
# us-east
# us-south
# wdc_preprod
# wdc_preprod_tls

region=all

certificate_duration_seconds=3600

metadata_retry_count=25

metadata_retry_interval=60
