# Dev Environment certs

# all - install all certificates
# region list - use any combination
# 7282
# dal_preprod
# dal_preprod_tls
# dev13
# dev13_tls
# dev42
# dev58
# dev80
# dev83
# dev92
# dev93
# wdc_preprod
# wdc_preprod_tls

region=all

certificate_duration_seconds=3600

metadata_retry_count=25

metadata_retry_interval=60
